{
  "comments": [
    {
      "key": {
        "uuid": "cd8a8734_434fa04b",
        "filename": "client/tests/on_error_test.py",
        "patchSetId": 2
      },
      "lineNbr": 224,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-06T08:27:21Z",
      "side": 1,
      "message": "I\u0027m curious when this value is expected.",
      "range": {
        "startLine": 224,
        "startChar": 43,
        "endLine": 224,
        "endChar": 57
      },
      "revId": "344ee48e9bca52b97d16da059fc6bc9f727c0edc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5fd885aa_38a2d4b8",
        "filename": "client/tests/on_error_test.py",
        "patchSetId": 2
      },
      "lineNbr": 224,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-06T08:52:59Z",
      "side": 1,
      "message": "This is come from\nhttps://source.chromium.org/chromium/infra/infra/+/master:luci/client/utils/on_error.py;l\u003d249;drc\u003d734d4c0af274e7db078b27e1b23eeadc034bacb0?originalUrl\u003dhttps:%2F%2Fcs.chromium.org%2F\n\n$ python2\nPython 2.7.18rc1 (default, Apr  7 2020, 09:34:05)\n[GCC 9.2.1 20191109] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\u003e\u003e\u003e import traceback\n\u003e\u003e\u003e traceback.format_exc()\n\u0027None\\n\u0027\n\n\n$ python3\nPython 3.7.7 (default, May 19 2020, 21:59:03)\n[GCC 9.3.0] on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\u003e\u003e\u003e import traceback\n\u003e\u003e\u003e traceback.format_exc()\n\u0027NoneType: None\\n\u0027",
      "parentUuid": "cd8a8734_434fa04b",
      "range": {
        "startLine": 224,
        "startChar": 43,
        "endLine": 224,
        "endChar": 57
      },
      "revId": "344ee48e9bca52b97d16da059fc6bc9f727c0edc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d0e7c49c_76e72764",
        "filename": "client/tests/on_error_test.py",
        "patchSetId": 2
      },
      "lineNbr": 224,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-06T09:00:53Z",
      "side": 1,
      "message": "Ack. It seems specific to this test.",
      "parentUuid": "5fd885aa_38a2d4b8",
      "range": {
        "startLine": 224,
        "startChar": 43,
        "endLine": 224,
        "endChar": 57
      },
      "revId": "344ee48e9bca52b97d16da059fc6bc9f727c0edc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}