{
  "comments": [
    {
      "key": {
        "uuid": "b6fe61d5_f4670df8",
        "filename": "client/libs/luci_context/luci_context.py",
        "patchSetId": 2
      },
      "lineNbr": 69,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-03-25T06:53:52Z",
      "side": 1,
      "message": "Could you add test?\n\nSeems not correct.\n$ python3\nPython 3.7.5 (default, Oct 27 2019, 15:43:29) \n[GCC 9.2.1 20190909] on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\u003e\u003e\u003e import six\n\u003e\u003e\u003e obj \u003d b\u0027\u0027\n\u003e\u003e\u003e if isinstance(obj, six.binary_type):\n...   obj.encode(\u0027utf-8\u0027)\n... \nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 2, in \u003cmodule\u003e\nAttributeError: \u0027bytes\u0027 object has no attribute \u0027encode\u0027\n\u003e\u003e\u003e",
      "revId": "75d23775c41d502240c7f99e5ff0fc02c74f8643",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3f627267_56ffee01",
        "filename": "client/libs/luci_context/luci_context.py",
        "patchSetId": 2
      },
      "lineNbr": 69,
      "author": {
        "id": 1116794
      },
      "writtenOn": "2020-03-26T04:07:59Z",
      "side": 1,
      "message": "I updated the if condition to only encode obj when it is running in Python2.\n\nThe problem is it will convert str to bytes in Python3, since six.text_type is str in Python3, which causes failed to find the luci context with given key, the key is str, not bytes.\n\nMy solution is conservative, I know you would like to avoid six.PY2 or six.PY3 in condition check, let me know if you have better idea to solve it, I am open to other ideas.",
      "parentUuid": "b6fe61d5_f4670df8",
      "revId": "75d23775c41d502240c7f99e5ff0fc02c74f8643",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "066162ec_6ff3686e",
        "filename": "client/libs/luci_context/luci_context.py",
        "patchSetId": 2
      },
      "lineNbr": 69,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-03-26T04:15:18Z",
      "side": 1,
      "message": "OK, but I still want you to write test for this change.\nTest written in\nhttps://cs.chromium.org/chromium/infra/luci/client/libs/luci_context/luci_context_test.py\nruns both in python2 and python3.",
      "parentUuid": "3f627267_56ffee01",
      "revId": "75d23775c41d502240c7f99e5ff0fc02c74f8643",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "775c3ed0_af58001e",
        "filename": "client/libs/luci_context/luci_context.py",
        "patchSetId": 2
      },
      "lineNbr": 69,
      "author": {
        "id": 1116794
      },
      "writtenOn": "2020-03-26T05:39:06Z",
      "side": 1,
      "message": "Added unit tests for _to_utf8 API.",
      "parentUuid": "066162ec_6ff3686e",
      "revId": "75d23775c41d502240c7f99e5ff0fc02c74f8643",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}