{
  "comments": [
    {
      "key": {
        "uuid": "5d09cd6e_853693b2",
        "filename": "client/cipd.py",
        "patchSetId": 3
      },
      "lineNbr": 440,
      "author": {
        "id": 1000487
      },
      "writtenOn": "2019-11-28T16:41:39Z",
      "side": 1,
      "message": "call()? So if this fails, it doesn\u0027t hide the underlying error.",
      "range": {
        "startLine": 440,
        "startChar": 19,
        "endLine": 440,
        "endChar": 29
      },
      "revId": "b240aa58caa3818737616e2d333e6549d6d50ad0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}