{
  "comments": [
    {
      "key": {
        "uuid": "64b3a849_1888a69f",
        "filename": "client/tests/run_isolated_smoke_test.py",
        "patchSetId": 3
      },
      "lineNbr": 236,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-15T02:58:22Z",
      "side": 1,
      "message": "I think it is not necessary to ignore exception here?",
      "revId": "fdb4519f1076ed0a239899a717f6656ed89d7257",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}